# Generated by Django 5.2 on 2025-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description_short', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное описание')),
                ('coordinates_lng', models.FloatField(verbose_name='Координаты долготы')),
                ('coordinates_lat', models.FloatField(verbose_name='Координаты широты')),
            ],
        ),
    ]
