# Generated by Django 5.2 on 2025-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(max_length=200, verbose_name='Короткое описание'),
        ),
    ]
