# Generated by Django 5.2 on 2025-07-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='', max_length=50, verbose_name='place id'),
            preserve_default=False,
        ),
    ]
