# Generated by Django 5.2 on 2025-07-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_picture',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='places.place', verbose_name='Локация'),
        ),
    ]
