# Generated by Django 5.2 on 2025-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_picture_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='place_picture',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Наименование'),
        ),
    ]
