# Generated by Django 5.2 on 2025-07-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_options_alter_place_picture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': 'Картинка'},
        ),
        migrations.AlterModelOptions(
            name='place_picture',
            options={'ordering': ['number'], 'verbose_name': 'Картинка'},
        ),
    ]
