# Generated by Django 5.2 on 2025-07-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_options_alter_place_picture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='place_picture',
            options={'ordering': ['number'], 'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
