# Generated by Django 5.2 on 2025-07-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_place_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
