# Generated by Django 5.2 on 2025-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_remove_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_picture',
            name='picture',
            field=models.ImageField(upload_to='place_pictures/', verbose_name='Загруженная фотография'),
        ),
    ]
