# Generated by Django 5.2 on 2025-07-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_place_picture_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place_picture',
            options={'ordering': ['number'], 'verbose_name': 'Загруженные фотографии'},
        ),
    ]
