# Generated by Django 5.2 on 2025-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_alter_place_picture_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_picture',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
