# Generated by Django 5.2 on 2025-07-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_place_picture_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place_picture',
            new_name='PlacePicture',
        ),
    ]
