# Generated by Django 5.2 on 2025-07-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_alter_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepicture',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
